kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: test
  labels:
    app: test

spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
        - name: nginxcontainer
          image: >-
                  toshrajbhardwaj/ra-auth:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: 1500m
              memory: 3Gi
          envFrom:
            - configMapRef:
                name: auth
            - secretRef:
                name: auth
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
              - name: regcred
      terminationGracePeriodSeconds: 30
      securityContext: {}
