kind: Service
apiVersion: v1
metadata:
  name: ra-auth
  namespace: test
  labels:
    app: ra-auth
    app.kubernetes.io/component: ra-auth
    app.kubernetes.io/instance: ra-auth
    app.kubernetes.io/part-of: auth-app
    app.openshift.io/runtime-version: sec-fix
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: ra-auth
    deploymentconfig: ra-auth
  clusterIP: 10.96.0.235
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

