kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ra-db-detection-shared-volume
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: ra-db-detection-shared-volume
  storageClassName: odf-lvm-vg1
  volumeMode: Block
