kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ra-db-detection-shared-volume
  namespace: ar-am
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: pvc-80e14044-74df-4eb6-ac05-2c6efdb4690f
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Block
