kind: Deployment
apiVersion: apps/v1
metadata:
  name: ra-coturn
  namespace: test
  labels:
    app: ra-coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ra-coturn
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ra-coturn
    spec:
      volumes:
        - name: ra-coturn-1
          emptyDir: {}
      containers:
        - resources:
            limits:
              cpu: '8'
              memory: 32Gi
            requests:
              cpu: '3'
              memory: 8Gi
          terminationMessagePath: /dev/termination-log
          name: ra-coturn
          ports:
            - containerPort: 3478
              protocol: TCP
            - containerPort: 3478
              protocol: UDP
            - containerPort: 49100
              protocol: UDP
            - containerPort: 49101
              protocol: UDP
            - containerPort: 49102
              protocol: UDP
            - containerPort: 49103
              protocol: UDP
            - containerPort: 49104
              protocol: UDP
          imagePullPolicy: Always
          volumeMounts:
            - name: ra-coturn-1
              mountPath: /var/lib/coturn
          terminationMessagePolicy: File
          image: >-
                 toshrajbhardwaj/coturn:latest
          args:
            - '-n'
            - '--log-file=stdout'
            - '--listening-port=3478'
            - '--tls-listening-port=5349'
            - '--fingerprint'
            - '--verbose'
            - '--user=vodafone:capgemini'
            - '--cipher-list=All'
            - '--realm=capgemini.com'
            - '--min-port=49100'
            - '--max-port=49104'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
              - name: regcred
      securityContext: {}
