---
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80


resources:
   limits:
     cpu: 100m
     memory: 2Gi
   requests:
     cpu: 100m
     memory: 1Gi

labels:
   app: myapp


selector:
   app: myapp
