kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-shared-volume
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pvc-1c4df273-7087-4b1b-afb2-a0fe1b83ffd4
  storageClassName: odf-lvm-vg1
  volumeMode: Block
