kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-shared-volume
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: local-pv-2390ce18
  storageClassName: myvol
  volumeMode: Block
