kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-shared-volume
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: ra-storage
  storageClassName: odf-lvm-vg1
  volumeMode: Block
