kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-shared-volume
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pvc-61c9ae42-b3d2-41e8-b15c-bd0927dd1f34
  storageClassName: odf-lvm-vg1
  volumeMode: Block
