kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-shared-volume
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: local-pv-c131e32b
  storageClassName: myvol
  volumeMode: Block
