kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-shared-volume
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: db-shared-vol
  storageClassName: odf-lvm-vg1
  volumeMode: Block
